# Generated by Django 5.2.15 on 2026-06-18 11:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_without_sale', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField()),
                ('inventory_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dead_stock_snapshots', to='products.product', unique=True)),
            ],
            options={
                'ordering': ['-detected_at'],
                'get_latest_by': 'detected_at',
            },
        ),
        migrations.CreateModel(
            name='SeasonalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_events', to='products.productcategory')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_promised_lead_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_actual_lead_time', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_delay_days', models.DecimalField(decimal_places=2, max_digits=6)),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_orders', models.PositiveIntegerField()),
                ('snapshot_date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-snapshot_date', 'supplier__name'],
                'unique_together': {('supplier', 'snapshot_date')},
            },
        ),
    ]
