# Generated by Django 5.2.15 on 2026-06-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorder_ordered_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reorderrecommendation',
            options={'ordering': ['-priority_score', '-generated_at']},
        ),
        migrations.AddField(
            model_name='reorderrecommendation',
            name='expected_restock_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reorderrecommendation',
            name='priority_level',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='reorderrecommendation',
            name='priority_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reorderrecommendation',
            name='unit_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
