# Generated by Django 5.2.15 on 2026-06-28 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_recommendation_profit_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reorderrecommendation',
            options={'ordering': ['-generated_at']},
        ),
        migrations.RemoveField(
            model_name='reorderrecommendation',
            name='expected_restock_profit',
        ),
        migrations.RemoveField(
            model_name='reorderrecommendation',
            name='priority_level',
        ),
        migrations.RemoveField(
            model_name='reorderrecommendation',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='reorderrecommendation',
            name='unit_profit',
        ),
        migrations.CreateModel(
            name='ProfitAdvisorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recommended_spending', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_profit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recommended_count', models.PositiveIntegerField()),
                ('explanation', models.TextField()),
                ('recommended_products', models.JSONField(default=list)),
                ('deferred_products', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_advisor_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profit advisor analyses',
            },
        ),
    ]
